FROM eclipse-temurin:23-jdk

RUN apt-get update && \
    apt-get install -y maven

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

RUN mvn clean package

EXPOSE 8080

CMD ["mvn", "spring-boot:run"]
